variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
resources:
  pipelines:
  - pipeline: PipelineNotFound
    source: PipelineNotFound
    trigger:
      branches:
        include:
        - main
  repositories:
  - repository: self
    type: git
    ref: main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-16.04
  steps:
  - checkout: self
  - task: MavenAuthenticate@0
    displayName: Maven Authenticate
    inputs:
      artifactsFeeds: webapp
  - task: Maven@3
    displayName: Maven pom.xml
    inputs:
      mavenPOMFile: $(BuildParameters.mavenPOMFile)
      mavenFeedAuthenticate: true
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**/*.jar'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
...
